site_name: 'Reginald: a simple Slack bot written in Python'
dev_addr: '127.0.0.1:9000'
docs_dir: .

nav:
  - Home: README.md
  - Models: MODELS.md
  - Configuration: ENVIRONMENT_VARIABLES.md
  - Issues: https://github.com/alan-turing-institute/reginald/issues
  - Reference: reference/

repo_url: https://github.com/alan-turing-institute/reginald/

watch:
  - docs

theme:
  name: material
  features:
    - content.code.copy
    - content.tabs.link
  palette:
    # Palette toggle for automatic mode
    - media: '(prefers-color-scheme)'
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search:
      lang: en
  - same-dir
  # - include-markdown
  # - markdown-exec
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: DOC_STRINGS.md
  - section-index
  - autorefs

  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: numpy
          paths: [.]
          options:
            separate_signature: true
            show_signature_annotations: true
            annotations_path: brief
            line_length: 80
            signature_crossrefs: true
            merge_init_into_classes: true

markdown_extensions:
  - smarty
  - admonition
  - pymdownx.details
  - abbr
  - attr_list
  - tables
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.magiclink
#
# extra_css:
#   - css/code_select.css
