[tool.poetry]
name = "reginald-slack"
version = "0.1.0"
description = "A Slack bot for REG Hack Week 2023"
authors = ["evelinag <evelina@evelinag.com>",
           "James Robinson <jrobinson@turing.ac.uk>",
           "Ryan Chan <rchan@turing.ac.uk>",
           "Markus Hauru <mhauru@turing.ac.uk>",
           "May Yong <myong@turing.ac.uk>",
           "James Bishop <jbishop@turing.ac.uk>",
           "Tomas Lazauskas <tlazauskas@turing.ac.uk>",
           "David Beavan <dbeavan@turing.ac.uk>",
           "Levan Bokeria <lbokeria@turing.ac.uk>",
           "Martin O'Reilly <moreilly@turing.ac.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
adapter-transformers = "^3.2.1"
datasets = "^2.12.0"
einops = "^0.6.1"
faiss-cpu = "^1.7.4"
gradio = "^3.34.0"
langchain = "0.0.276"
llama-index = "0.8.14"
nbconvert = "^7.5.0"
openai = "^0.27.8"
pandas = "^2.0.2"
pulumi = "^3.70.0"
pulumi-azure-native = "^1.103.0"
sentence-transformers = "^2.2.2"
slack-sdk = "^3.21.3"
tokenizers = "^0.13.3"
torch = [
  { version = "^2.0.1", markers = "sys_platform != 'linux'", source = "PyPI", optional=true },
  { version = "^2.0.1+cpu", markers = "sys_platform == 'linux'", source = "torchcpu", optional=true }
]
transformers = "=4.30.2"
ipykernel = "^6.23.2"
xformers = { version="^0.0.20", optional=true }
llama-cpp-python = "0.1.76"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
isort = "^5.12.0"
pre-commit = "^3.3.2"

[tool.poetry.extras]
azure = [
    "pulumi",
    "pulumi-azure-native"
]
bot = [
    "adapter-transformers",
    "bitsandbytes",
    "datasets",
    "einops",
    "faiss-cpu",
    "gradio",
    "langchain",
    "llama-index",
    "nbconvert",
    "openai",
    "sentence-transformers",
    "slack-sdk",
    "tokenizers",
    "torch",
    "transformers"
]

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[[tool.poetry.source]]
name = "torchcpu"
url = "https://download.pytorch.org/whl/cpu/"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
