[tool.poetry]
name = "reginald-slack"
version = "0.1.0"
description = "A Slack bot for REG Hack Week 2023"
authors = ["evelinag <evelina@evelinag.com>",
           "James Robinson <jrobinson@turing.ac.uk>",
           "Ryan Chan <rchan@turing.ac.uk>",
           "Rosie Wood <rwood@turing.ac.uk>",
           "Markus Hauru <mhauru@turing.ac.uk>",
           "May Yong <myong@turing.ac.uk>",
           "James Bishop <jbishop@turing.ac.uk>",
           "Tomas Lazauskas <tlazauskas@turing.ac.uk>",
           "David Beavan <dbeavan@turing.ac.uk>",
           "Levan Bokeria <lbokeria@turing.ac.uk>",
           "Martin O'Reilly <moreilly@turing.ac.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
adapter-transformers = { version="^3.2.1", optional=true }
datasets = { version="^2.12.0", optional=true }
einops = { version="^0.6.1", optional=true }
faiss-cpu = { version="^1.7.4", optional=true }
gradio = { version="^3.34.0", optional=true }
langchain = "^0.0.278"
llama-index = "^0.8.25"
llama-cpp-python = "^0.2.2"
llama-hub = "^0.0.31"
nbconvert = { version="^7.5.0", optional=true }
openai = { version="^0.27.8", optional=true }
pandas = "^2.0.2"
pulumi = { version="^3.70.0", optional=true }
pulumi-azure-native = { version="^1.103.0", optional=true }
sentence-transformers = { version="^2.2.2", optional=true }
slack-sdk = { version ="^3.21.3", optional=true }
tokenizers = "^0.13.3"
torch = [
  { version = "^2.0.1", markers = "sys_platform != 'linux'", source = "PyPI", optional=true },
  { version = "^2.0.1+cpu", markers = "sys_platform == 'linux'", source = "torchcpu", optional=true }
]
transformers = "=4.30.2"
ipykernel = "^6.23.2"
xformers = { version="^0.0.20", optional=true }
ipywidgets = "^8.1.0"
gitpython = "^3.1.36"
accelerate = { version="^0.22.0", optional=true }

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
isort = "^5.12.0"
pre-commit = "^3.3.2"

[tool.poetry.extras]
huggingface_llm = [
    "accelerate"
]
azure = [
    "pulumi",
    "pulumi-azure-native"
]
bot = [
    "adapter-transformers",
    "bitsandbytes",
    "datasets",
    "einops",
    "faiss-cpu",
    "gradio",
    "langchain",
    "nbconvert",
    "openai",
    "sentence-transformers",
    "slack-sdk",
    "torch",
]

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[[tool.poetry.source]]
name = "torchcpu"
url = "https://download.pytorch.org/whl/cpu/"
priority = "explicit"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
