[tool.poetry]
name = "reginald-slack"
version = "0.1.0"
description = "A Slack bot for REG Hack Week 2023"
authors = ["evelinag <evelina@evelinag.com>",
           "James Robinson <jrobinson@turing.ac.uk>",
           "Ryan Chan <rchan@turing.ac.uk>",
           "Markus Hauru <mhauru@turing.ac.uk>",
           "May Yong <myong@turing.ac.uk>",
           "James Bishop <jbishop@turing.ac.uk>",
           "Tomas Lazauskas <tlazauskas@turing.ac.uk>",
           "David Beavan <dbeavan@turing.ac.uk>",
           "Levan Bokeria <lbokeria@turing.ac.uk>",
           "Martin O'Reilly <moreilly@turing.ac.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
accelerate = { version="^0.20.3", optional=true }
adapter-transformers = { version="^3.2.1", optional=true }
datasets = { version="^2.12.0", optional=true }
einops = { version="^0.6.1", optional=true }
faiss-cpu = { version="^1.7.4", optional=true }
gradio = { version="^3.34.0", optional=true }
langchain = { version="^0.0.198", optional=true }
llama-index = { version="^0.6.23", optional=true }
openai = { version="^0.27.8", optional=true }
pandas = { version="^2.0.2", optional=true }
pulumi = { version="^3.70.0", optional=true }
pulumi-azure-native = { version="^1.103.0", optional=true }
sentence-transformers = { version="^2.2.2", optional=true }
slack-sdk = { version ="^3.21.3", optional=true }
tokenizers = { version="^0.13.3", optional=true }
torch = { version="^2.0.1", optional=true }
transformers = { version="^4.30.1", optional=true }
ipykernel = "^6.23.2"

[tool.poetry.dev-dependencies]
black = "^23.3.0"
isort = "^5.12.0"
pre-commit = "^3.3.2"

[tool.poetry.extras]
azure = [
    "pulumi",
    "pulumi-azure-native"
]
bot = [
    "langchain",
    "llama_index",
    "openai",
    "pandas",
    "slack-sdk",
    "torch",
    "transformers"
]
model = [
    "accelerate",
    "adapter-transformers",
    "datasets",
    "einops",
    "faiss-cpu",
    "gradio",
    "langchain",
    "llama-index",
    "sentence-transformers",
    "tokenizers",
    "torch",
    "transformers"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
