[tool.poetry]
name = "reginald"
version = "0.1.0"
description = "A Slack bot for REG Hack Week 2023"
authors = ["Evelina Gabasova <evelina@evelinag.com>",
           "James Robinson <jrobinson@turing.ac.uk>",
           "Ryan Chan <rchan@turing.ac.uk>",
           "Rosie Wood <rwood@turing.ac.uk>",
           "Markus Hauru <mhauru@turing.ac.uk>",
           "May Yong <myong@turing.ac.uk>",
           "James Bishop <jbishop@turing.ac.uk>",
           "Tomas Lazauskas <tlazauskas@turing.ac.uk>",
           "David Beavan <dbeavan@turing.ac.uk>",
           "Levan Bokeria <lbokeria@turing.ac.uk>",
           "Martin O'Reilly <moreilly@turing.ac.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
accelerate = "^0.23.0"
bitsandbytes = { version="^0.41.1", optional=true }
datasets = { version="^2.12.0", optional=true }
faiss-cpu = { version="^1.7.4", optional=true }
fastapi = { version="^0.103.1", optional=true }
gitpython = "^3.1.36"
gradio = { version="^3.34.0", optional=true }
httpx = { version="^0.25.0", optional=true }
ipykernel = { version="^6.23.2", optional=true }
langchain = "^0.0.294"
llama-cpp-python = "^0.2.7"
llama-index = "^0.8.29.post1"
llama-hub = "^0.0.31"
nbconvert = {version = "^7.8.0", optional = true}
nest_asyncio = "^1.5.8"
openai = "^0.27.8"
pandas = "^2.0.2"
pulumi = { version="^3.70.0", optional=true }
pulumi-azure-native = { version="^1.103.0", optional=true }
pydantic = {version = "^2.4.1", optional=true }
requests = {version = "^2.31.0", optional=true }
safetensors = "^0.3.3"
slack-sdk = "^3.21.3"
sentence-transformers = "^2.2.2"
torch = [
  { version = "^2.0.1", markers = "sys_platform != 'linux'", source = "PyPI" },
  { version = "^2.0.1+cpu", markers = "sys_platform == 'linux'", source = "torchcpu" }
]
transformers = "^4.33.2"
uvicorn = { version="^0.23.2", optional=true }

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
isort = "^5.12.0"
pre-commit = "^3.3.2"

[tool.poetry.extras]
api_bot = [
    "fastapi",
    "pydantic",
    "requests",
    "uvicorn",
]
azure = [
    "pulumi",
    "pulumi-azure-native",
]
ft_notebooks = [
    "datasets",
    "faiss-cpu",
    "ipykernel",
]
llama_index_notebooks = [
    "bitsandbytes",
    "gradio",
    "ipykernel",
    "nbconvert",
    "httpx"
]

[tool.poetry.scripts]
reginald_run = "reginald.run:cli"
reginald_run_api_bot = "reginald.slack_bot.setup_bot:cli"
reginald_run_api_llm = "reginald.models.app:main"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[[tool.poetry.source]]
name = "torchcpu"
url = "https://download.pytorch.org/whl/cpu/"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
