[tool.poetry]
name = "reginald-slack"
version = "0.1.0"
description = "A Slack bot for REG Hack Week 2023"
authors = ["evelinag <evelina@evelinag.com>", "James Robinson <jrobinson@turing.ac.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
slack-sdk = "^3.21.3"

[tool.poetry.dev-dependencies]
black = "^23.3.0"
isort = "^5.12.0"
pre-commit = "^3.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
